"""generate_dict: the site_config.yaml `dictionaries:` registry, dict.folder
validation, and the generated dict/meta.yaml + dict/<folder>/meta.yaml."""
from pathlib import Path
from types import SimpleNamespace

import pytest
import yaml

import generate_dict as gd

REGISTRY = {"kavya": "Kavya", "plays": "Nataka"}


def fake_text(meta, d="kavya/padya/ks"):
    return SimpleNamespace(meta=meta, dir=Path(d), slug=Path(d).name)


# --- load_dictionaries -----------------------------------------------------

def test_load_dictionaries_preserves_order():
    cfg = {"dictionaries": [{"name": "Nataka", "folder": "plays"}, {"name": "Kavya", "folder": "kavya"}]}
    assert list(gd.load_dictionaries(cfg).items()) == [("plays", "Nataka"), ("kavya", "Kavya")]


def test_load_dictionaries_strips_whitespace_and_allows_devanagari_names():
    cfg = {"dictionaries": [{"name": " काव्यकोशः ", "folder": " kavya "}]}
    assert gd.load_dictionaries(cfg) == {"kavya": "काव्यकोशः"}


def test_load_dictionaries_absent_is_empty():
    assert gd.load_dictionaries({}) == {}


@pytest.mark.parametrize("raw,needle", [
    ({"name": "Kavya"}, "must be a list"),
    ([["kavya"]], "must be a mapping"),
    ([{"name": "Kavya"}], "non-empty name: and folder:"),
    ([{"folder": "kavya"}], "non-empty name: and folder:"),
    ([{"name": "", "folder": "kavya"}], "non-empty name: and folder:"),
    ([{"name": "A", "folder": "k"}, {"name": "B", "folder": "k"}], "more than once"),
    ([{"name": "A", "folder": "a/b"}], "plain directory name"),
    ([{"name": "A", "folder": ".."}], "plain directory name"),
    ([{"name": "A", "folder": "meta.yaml"}], "plain directory name"),
])
def test_load_dictionaries_rejects_bad_config(raw, needle):
    with pytest.raises(gd.DictConfigError) as exc:
        gd.load_dictionaries({"dictionaries": raw})
    assert needle in str(exc.value)


# --- text_dict_folder ------------------------------------------------------

def test_text_with_declared_folder():
    assert gd.text_dict_folder(fake_text({"dict": {"folder": "kavya"}}), REGISTRY) == "kavya"


@pytest.mark.parametrize("meta", [{}, {"dict": None}, {"dict": {}}, {"dict": {"folder": ""}}])
def test_text_without_folder(meta):
    assert gd.text_dict_folder(fake_text(meta), REGISTRY) == ""


def test_undeclared_folder_fails():
    with pytest.raises(gd.DictConfigError) as exc:
        gd.text_dict_folder(fake_text({"dict": {"folder": "kayva"}}), REGISTRY)
    msg = str(exc.value)
    assert "'kayva'" in msg and "kavya/padya/ks/meta.yaml" in msg and "kavya, plays" in msg


def test_undeclared_folder_fails_with_empty_registry():
    with pytest.raises(gd.DictConfigError) as exc:
        gd.text_dict_folder(fake_text({"dict": {"folder": "kavya"}}), {})
    assert "declared: none" in str(exc.value)


def test_dict_block_must_be_mapping():
    with pytest.raises(gd.DictConfigError):
        gd.text_dict_folder(fake_text({"dict": "kavya"}), REGISTRY)


# --- build_meta_files / dump / write ---------------------------------------

def test_build_meta_files():
    files = gd.build_meta_files({"plays": ["as"], "kavya": ["ks", "ka"]}, REGISTRY)
    assert files == {
        "meta.yaml": {"dictionaries": ["kavya", "plays"]},  # registry order, not insertion order
        "kavya/meta.yaml": {"name": "Kavya", "folders": ["ks", "ka"]},
        "plays/meta.yaml": {"name": "Nataka", "folders": ["as"]},
    }


def test_build_meta_files_skips_inactive_folders():
    files = gd.build_meta_files({"kavya": ["ks"], "plays": []}, REGISTRY)
    assert files == {"meta.yaml": {"dictionaries": ["kavya"]}, "kavya/meta.yaml": {"name": "Kavya", "folders": ["ks"]}}


def test_build_meta_files_nothing_written():
    assert gd.build_meta_files({}, REGISTRY) == {"meta.yaml": {"dictionaries": []}}


def test_dump_meta_yaml_exact_format():
    assert gd.dump_meta_yaml({"name": "Kavya", "folders": ["ks", "ka"]}) == (
        "# Generated by generate_dict.py — do not edit by hand.\n"
        "name: Kavya\nfolders:\n  - ks\n  - ka\n"
    )
    assert gd.dump_meta_yaml({"dictionaries": ["kavya", "plays"]}).endswith("dictionaries:\n  - kavya\n  - plays\n")


def test_dump_meta_yaml_unicode_and_round_trip():
    data = {"name": "काव्यम्: 'x'", "folders": ["ks", "yes", "01"]}
    text = gd.dump_meta_yaml(data)
    assert "काव्यम्" in text  # not \u-escaped
    assert yaml.safe_load(text) == data  # special values quoted correctly


def test_write_meta_files(tmp_path):
    gd.write_meta_files(tmp_path, {"kavya": ["ks"]}, REGISTRY)
    assert yaml.safe_load((tmp_path / "meta.yaml").read_text(encoding="utf-8")) == {"dictionaries": ["kavya"]}
    assert yaml.safe_load((tmp_path / "kavya" / "meta.yaml").read_text(encoding="utf-8")) == {
        "name": "Kavya", "folders": ["ks"],
    }
    assert not (tmp_path / "plays").exists()
