"""HAND-MAINTAINED, not regenerated by generate_indices.py — referenced by
`module_name:` from the `macros:` plugin entry in mkdocs.yml's static
template (MKDOCS_STATIC_TMPL / build_mkdocs_static() in
scripts/generate_indices.py), the same convention as mkdocs_hooks.py's
`hooks:` entry.

Registers custom Jinja macros usable from any source .md file's body —
evaluated by mkdocs-macros-plugin during the real `mkdocs build` pass
(after generate_indices.py has already written docs/, and after it's
decided things like chapter_display_style: full_chapter vs sections —
see that config's own comment in generate_indices.py), the same pass
that already handles `{% set var = "..." %}` and `{{ page.meta.* }}` —
see mkdocs.yml's own comment for why authors use `{% set %}` rather than
frontmatter here (generated pages carry none).
"""

import posixpath


def define_env(env):
    @env.macro
    def xref(target: str) -> str:
        """Cross-reference link to another page anywhere in the site.
        Returns a real relative link (`../../../topics/shabdashakti.md`)
        computed fresh, on every build, from wherever the CURRENTLY
        RENDERING page's own output actually lands — so content authors
        never need to count `../` segments by hand, and the same call
        keeps resolving correctly no matter how deep that ends up being
        (e.g. a chapter's `chapter_display_style: sections` output sits
        one directory level deeper than `full_chapter` — see that
        config's own comment in generate_indices.py — this macro
        doesn't need to know or care which one is in effect).

        `target` is a docs_dir-root-relative path to the target page's
        source .md file, e.g. "shastra/topics/shabdashakti.md" — the
        same path you'd have written as a root-absolute link
        ("/shastra/topics/shabdashakti/"), just without the leading
        slash and with the real .md name. Forgiving of a leading "/"
        and a missing ".md" extension, so an existing absolute link can
        be adapted by wrapping the path here and dropping the leading
        and trailing slash.

        Use it exactly where the absolute path used to go, keeping
        markdown link syntax and any #anchor as plain text around it —
        this macro's only job is the path, not the link/anchor text:

            [लक्षणा]({{ xref("shastra/topics/shabdashakti.md") }}#लक्षणा)

        A root-absolute link is silently excluded from MkDocs' own link
        validation (see the INFO message you get from writing one) and
        breaks under any deployment not served at the domain root —
        including this project's own GitHub Pages project-site path and
        its site-offline zip artifact for local/offline viewing.

        The relative path is computed from `env.page.file.src_uri` (the
        docs_dir-relative .md path of the CURRENTLY RENDERING page) —
        deliberately NOT `env.page.url` (MkDocs' final clean output
        URL), which sits one directory level deeper under the default
        `use_directory_urls: true` (a page's .md file gets its own
        directory named after it in the output). A raw Markdown
        `[text](path.md)` link is resolved by MkDocs against the
        SOURCE file's own directory, not that output URL — the exact
        same math this project's own `rel_link()` in
        generate_indices.py already uses for its auto-generated
        back-links, mirrored here for author-written ones.
        """
        target = target.strip().lstrip("/")
        if target.endswith("/"):
            target = target[:-1]
        if not target.endswith(".md"):
            target = f"{target}.md"
        current_dir = posixpath.dirname(env.page.file.src_uri)
        return posixpath.relpath(target, start=current_dir or ".")
