"""HAND-MAINTAINED, not regenerated by generate_indices.py — referenced by
name from the `hooks:` list in mkdocs.yml's static template
(MKDOCS_STATIC_TMPL / build_mkdocs_static() in scripts/generate_indices.py).

Why this exists: the `toc` markdown extension's default slugify only keeps
`\\w` characters, and Python's `\\w` does NOT include Unicode combining
marks (category Mn/Mc — e.g. Devanagari vowel signs and the virama). That
silently mangles every Devanagari heading into a corrupted, sometimes
near-empty anchor id ("प्रभेदाः" -> "परभद", dropping the vowel signs and
virama entirely) — so heading permalinks look fine visually but a link
from elsewhere to that heading (e.g. `[x](../topic/#प्रभेदाः)`) can never
resolve, since the real id on the page isn't the heading text at all.

pymdownx.slugs.slugify (the usual off-the-shelf Unicode-aware slugify)
has the exact same problem — it also filters by `\\w`. So this project
uses its own, which additionally keeps any character in category Mn/Mc/Me
(combining marks) alongside letters/digits, and lowercases + turns
whitespace into `sep`. A heading's rendered permalink id is then simply
its own text (case-folded, spaces to hyphens) — readable, predictable,
and exactly what you'd type by hand when linking to it from elsewhere:
`[x](../topic-page/#प्रभेदाः)`.

Referencing a local Python file this way — rather than a plain
`!!python/name:some.module.func` in mkdocs.yml directly — is deliberate:
`!!python/name:` only resolves genuinely importable/installed packages
(e.g. pymdownx, already a real pip dependency here); it can't resolve an
arbitrary project-local file. MkDocs' `hooks:` mechanism exists
specifically for this — it imports a local file relative to mkdocs.yml
and calls its on_*() event functions, so a local file (no packaging, no
install step) can still reach into the build config."""

import re
import unicodedata

_RE_TAGS = re.compile(r"</?[^>]*>", re.UNICODE)
_RE_WS = re.compile(r"\s+", re.UNICODE)
_COMBINING_CATEGORIES = ("Mn", "Mc", "Me")


def devanagari_safe_slugify(text: str, sep: str) -> str:
    """Drop-in replacement for the `toc` extension's `slugify:` option.
    Keeps letters/digits/underscore (`str.isalnum()`) AND Unicode
    combining marks, so composed scripts like Devanagari survive intact;
    everything else (punctuation, quotes, HTML tags already stripped
    above) is dropped; runs of whitespace become `sep`."""
    text = _RE_TAGS.sub("", text)
    text = unicodedata.normalize("NFC", text).strip().lower()
    kept = "".join(
        ch for ch in text
        if ch.isalnum() or ch in "-_" or ch.isspace() or unicodedata.category(ch) in _COMBINING_CATEGORIES
    )
    return _RE_WS.sub(sep, kept)


def on_config(config, **kwargs):
    """MkDocs hook event — runs once per build, after mkdocs.yml is
    parsed. Overrides the `toc` extension's slugify function in place;
    everything else about the `toc:` config (permalink: true, etc.) is
    untouched."""
    config["mdx_configs"].setdefault("toc", {})["slugify"] = devanagari_safe_slugify
    return config
